# Generated by Django 3.2.9 on 2021-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.CharField(max_length=200)),
                ('show_date', models.DateTimeField(verbose_name='show date')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='films',
            field=models.ManyToManyField(to='cinemas.Film'),
        ),
    ]
