# Generated by Django 3.2.9 on 2021-12-04 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_auto_20211203_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='films',
        ),
        migrations.RemoveField(
            model_name='film',
            name='show_date',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='session time')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.film')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='sessions',
            field=models.ManyToManyField(to='cinemas.Session'),
        ),
    ]
