# Generated by Django 3.2.9 on 2021-12-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_auto_20211204_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='name',
        ),
    ]
