# Generated by Django 3.2.9 on 2021-12-04 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0006_cinemacomment_filmcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemacomment',
            name='film',
        ),
        migrations.AddField(
            model_name='cinemacomment',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema'),
            preserve_default=False,
        ),
    ]
